---
version: 1

# A pager program to send command output to, e.g. "less". Set the value to "cat" to disable the pager.
pager: bat

# What editor `gh` should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor: nvim

# When to interactively prompt. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prompt: enabled

# What web browser `gh` should use when opening URLs. If blank, will refer to environment.
browser: ''

# Aliases allow you to create nicknames for `gh` commands
aliases:

  # PR related aliases
  co: pr checkout
  prc: pr create
  prd: '!GH_PAGER="diffnav" gh pr diff'
  prv: pr view --web

  # Workflow related aliases
  rw: run watch
  rdl: run download

  # Repo related aliases
  v: browse --no-browser
  b: '!gh browse --no-browser | pbcopy'

  # Issue related aliases
  me: issues --assignee '@me' --state 'open'

  # Enhance related aliases
  e: '!ENHANCE_THEME="gruvbox_dark" gh enhance "$(gh pr view --jq ".url" --json "url")"'

  # Release related aliases
  rel: release view --jq '.[].name' --json 'name'
  rels: release list --jq '.[].name' --json 'name'
  reldl: '!gh release download $1'
  relrm: '!gh release delete $1 --yes --cleanup-tag'

  # Identity related aliases
  creds: '!cd ~/.config/gh && ln -nfs hosts-$1.yml hosts.yml && cd ~/.config/gama && ln -nfs config-$1.yaml config.yaml && gh auth status'

# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: ssh

# The path to a unix socket through which send HTTP connections. If blank, HTTP traffic will be handled by net/http.DefaultTransport.
http_unix_socket: ''

# vim: et ts=2 sts=2 sw=2 syntax=yaml
