# External repositories
[".local/share/bin/kanage"]
  url           = "https://raw.githubusercontent.com/myagoo/kanage/refs/heads/main/kanage"
  type          = "file"
  refreshPeriod = "168h"  # every week

[".cache/tmux/plugins/tpm-redux"]
  url           = "https://github.com/ryanmacg/tpm-redux"
  type          = "git-repo"
  refreshPeriod = "168h"  # every week

# External binaries
# [".local/bin/siggo"]  # leave comment as an example
#   url        = "https://github.com/derricw/siggo/releases/download/0.12.0/siggo-0.12.0-darwin-amd64.tar.gz"
#   type       = "file"
#   executable = true
#   [".local/bin/siggo".filter]
#     args    = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "bin/siggo"]
#     command = "tar"

# vim: et ts=2 sts=2 sw=2 syntax=toml
