# EXTERNAL REPOSITORIES
[".cache/tpm/tpm"]
  url  = "https://github.com/tmux-plugins/tpm"
  type = "git-repo"

# [".cache/color-scripts"]
#   url           = "https://gitlab.com/dwt1/shell-color-scripts"
#   type          = "git-repo"
#   refreshPeriod = "24h"

# [".cache/pokemon-scripts"]
#   url           = "https://gitlab.com/phoneybadger/pokemon-colorscripts"
#   type          = "git-repo"
#   refreshPeriod = "24h"

# EXTERNAL BINARIES
# [".local/bin/siggo"]  # leave comment as an example
#   url        = "https://github.com/derricw/siggo/releases/download/0.12.0/siggo-0.12.0-darwin-amd64.tar.gz"
#   type       = "file"
#   executable = true
#   [".local/bin/siggo".filter]
#     args    = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "bin/siggo"]
#     command = "tar"
