[group('cognitive-services')]
[group('azure')]
[doc('List the deployments on a resource group.')]
az-cs-ls:
  az cognitiveservices account list-deleted --output 'table'

# [group('cognitive-services')]
# [group('azure')]
# [doc('List the deployments on a resource group.')]
# az-cs-del:
#   az cognitiveservices account list-deleted --output 'table'
# 
# [group('cognitive-services')]
# [group('azure')]
# [doc('List the deployments on a resource group.')]
# az-cs-prune:
#   az cognitiveservices account purge --name '' --resource-group ''
