#!/usr/bin/env sh

# BAR SETTINGS
spacebar -m config background_color "0x801d2021"  # 0x80 transparency
spacebar -m config foreground_color "0xffbdae93"

# FONT SETTINGS
spacebar -m config text_font "Hack Nerd Font:Bold:14.0"
spacebar -m config icon_font "Hack Nerd Font:Regular:14.0"

# POWER SETTINGS
# spacebar -m config power_icon_strip "LOOL"
spacebar -m config power_icon_strip ""
spacebar -m config power_icon_color   "0xffd79921"
spacebar -m config battery_icon_color "0xffb8bb26"

# 
spacebar -m config dnd_icon       ""
spacebar -m config dnd_icon_color "0xfffbf1c7"

# SPACE SETTINGS
spacebar -m config space_icon ""
spacebar -m config space_icon_color "0xff98971a"
spacebar -m config space_icon_strip \
    01 02 03 04 05 06 07 08 09 10   \
    11 12 13 14 15 16 17 18 19 20   \
    21 22 23 24 25 26 27 28 29 30   \
    31 32 33 34 35 36 37 38 39 40

# POSITION SETTINGS
spacebar -m config height        26
spacebar -m config position      "top"
spacebar -m config spacing_left  25
spacebar -m config spacing_right 25

# CLOCK SETTINGS
spacebar -m config clock_icon       ""
spacebar -m config clock_format     "%d %b %Y | %R"
spacebar -m config clock_icon_color "0xff458588"
