# vim: syntax=toml

# PLUGINS TO LOAD AT START

[[plugins]]  # plugin manager
repo       = "shougo/dein.vim"

[[plugins]]  # plugin manager tui
repo       = "wsdjeg/dein-ui.vim"
depends_on = ["shougo/dein.vim"]

[[plugins]]  # linter for lsp
repo     = "neoclide/coc.nvim"
hook_add = """
    let g:coc_global_extensions = [
    \ 'coc-go',
    \ 'coc-sh',
    \ 'coc-git',
    \ 'coc-java',
    \ 'coc-toml',
    \ 'coc-yaml',
    \ 'coc-pyright',
    \ 'coc-floaterm',
    \ 'coc-highlight',
    \ 'coc-fzf-preview'
    \ ]
"""

[[plugins]]  # linter for lsp
repo       = "dense-analysis/ale"
hook_add   = """
    let g:ale_linters              = {
    \ 'go': [],
    \ 'python': ['flake8']
    \ }
    let g:ale_lint_on_enter        = 1
    let g:ale_lint_on_text_changed = 'never'
"""

[[plugins]]  # nvim-telescope/telescope.nvim
repo       = "nvim-lua/popup.nvim"

[[plugins]]  # nvim-telescope/telescope.nvim
repo       = "nvim-lua/plenary.nvim"

[[plugins]]  # nvim-telescope/telescope.nvim
repo       = "nvim-telescope/telescope-fzf-native.nvim"
build      = "make"

[[plugins]]  # fuzzy finder for nvim
repo       = "nvim-telescope/telescope.nvim"
depends_on = [
    "nvim-lua/popup.nvim",
    "nvim-lua/plenary.nvim",
    "nvim-telescope/telescope-fzf-native.nvim",
]
hook_add   = """
    nnoremap <leader>rg   :Telescope live_grep<CR>
    nnoremap <leader>gf   :Telescope git_files<CR>
    nnoremap <leader>ff   :Telescope find_files<CR>
    nnoremap <leader><CR> :Telescope buffers<CR>
"""

[[plugins]]  # floating terinal inside vim
repo       = "voldikss/vim-floaterm"
hook_add   = """
    hi Floaterm guibg=black
    hi FloatermBorder guibg=gray guifg=green
    let g:floaterm_title = '  $1/$2 '
    nnoremap <leader>ft                :FloatermFirst<CR>
    nnoremap <leader>ftn               :FloatermNew<CR>
    tnoremap <silent><F12> <C-\\><C-n> :FloatermToggle<CR>
"""

[[plugins]]  # lsp and tag viewer
repo       = "liuchengxu/vista.vim"
depends_on = []
hook_add   = ""

[[plugins]]  # git wrapper for vim
repo       = "tpope/vim-fugitive"
depends_on = []
hook_add   = ""

[[plugins]]  # smooth scrolling
repo       = "karb94/neoscroll.nvim"
depends_on = []
hook_add   = ""

[[plugins]]  # show minimap
repo       = "wfxr/minimap.vim"
depends_on = []
hook_add   = """
    nnoremap <leader>mt :MinimapToggle

    let g:minimap_width                = 10
    let g:minimap_git_colors           = 1
    let g:minimap_auto_start           = 0
    let g:minimap_highlight_search     = 1
    let g:minimap_auto_start_win_enter = 0
"""

[[plugins]]  # quickly comment and un-comment
repo       = "preservim/nerdcommenter"
depends_on = []
hook_add   = """
    let g:NERDSpaceDelims = 1
"""

[[plugins]]  # show key bindings
repo       = "folke/which-key.nvim"
depends_on = []
hook_add   = """
"""

# [[plugins]]  #  quickly traverse the buffer
# repo       = "easymotion/vim-easymotion"
# depends_on = []
# hook_add   = """
# """

[[plugins]]  #  highlight all pattern matches in easymotion
repo       = "haya14busa/incsearch-easymotion.vim"
depends_on = []
hook_add   = """
    map z/ <Plug>(incsearch-easymotion-/)
    map z? <Plug>(incsearch-easymotion-?)
    map zg/ <Plug>(incsearch-easymotion-stay)
"""

[[plugins]]  # highlight all pattern matches
repo       = "haya14busa/incsearch.vim"
depends_on = []
hook_add   = """
    map g/ <Plug>(incsearch-stay)
    map /  <Plug>(incsearch-forward)
    map ?  <Plug>(incsearch-backward)
"""

[[plugins]]  # show indent lines
repo       = "yggdroot/indentline"
depends_on = []
hook_add   = """
    let g:indentline_char_list = ['|', '¦', '┆', '┊']
"""

# [[plugins]]  # highlight parentheses
# repo       = "p00f/nvim-ts-rainbow"
# depends_on = []
# hook_add   = """
# """

[[plugins]]  # highlight yanked text
repo       = "machakann/vim-highlightedyank"
depends_on = []
hook_add   = """
    let g:highlightedyank_highlight_duration = -1
"""

[[plugins]]  # nerdfonts icons for vim
repo       = "kyazdani42/nvim-web-devicons"
depends_on = []
hook_add   = ""

[[plugins]]  # gray out inactive windows
repo       = "blueyed/vim-diminactive"
depends_on = []
hook_add   = ""

# [[plugins]]  # tab line
# repo       = "akinsho/nvim-bufferline.lua"
# depends_on = []
# hook_add   = ""

[[plugins]]  # status line
repo       = "vim-airline/vim-airline"
depends_on = ["sainnhe/gruvbox-material"]
hook_add   = """
    let g:airline_theme           = 'gruvbox_material'
    let g:airline_powerline_fonts = 1
"""

[[plugins]]  # start page with latest files
repo       = "mhinz/vim-startify"
depends_on = []
hook_add   = """
    let g:startify_files_number        = 15
    let g:startify_change_to_dir       = 1
    let g:startify_fortune_use_unicode = 1
"""

[[plugins]]  # theme with tree-sitter support
repo       = "sainnhe/gruvbox-material"
depends_on = []
hook_add   = """
    let g:gruvbox_material_visual                = 'reverse'
    let g:gruvbox_material_background            = 'medium'
    let g:gruvbox_material_enable_bold           = 1
    let g:gruvbox_material_enable_italic_comment = 1
"""
