# vim: syntax=toml

# PLUGINS TO ADD ON FILE LOAD

[[plugins]]
repo  = "fatih/vim-go"
on_ft = ["go"]

[[plugins]]
repo  = "cespare/vim-toml"
on_ft = ["toml"]

[[plugins]]
repo  = "jvirtanen/vim-hcl"
on_ft = ["hcl"]

[[plugins]]
repo  = "hashivim/vim-terraform"
on_ft = ["tf", "tfvars", "tfstate"]

[[plugins]]
repo  = "pearofducks/ansible-vim"
on_ft = ["yml", "yaml"]
