# Inspired by:
# - https://github.com/rothgar/awesome-tmux
# - https://github.com/dreamsofcode-io/tmux/blob/main/tmux.conf

# Setup plugin manager
set -g @plugin 'ryanmacg/tpm-redux'  # plugin manager

# Setup appearance plugins
set -g @plugin 'roosta/tmux-pop'  # flash the pane at certain color
    set -g @tmux-pop-color 'green'

# set -g @plugin '2Kabhishek/tmux2k'  # powerline theme
#     set -g @tmux2k-theme 'gruvbox'
#     set -g @tmux2k-icons-only false
#     set -g @tmux2k-start-icon ''
#     set -g @tmux2k-left-plugins 'git cpu ram'
#     set -g @tmux2k-right-plugins 'battery network time'
#     set -g @tmux2k-military-time true
#     set -g @tmux2k-show-powerline true

set -g @plugin 'fabioluciano/tmux-powerkit'
    set -g @powerkit_theme 'gruvbox'
    set -g @powerkit_plugins 'git,github,cloud,hostname,external_ip,ping,network'
    set -g @powerkit_bar_layout 'double'
    set -g @powerkit_transparent true
    set -g @powerkit_theme_variant 'dark'
    set -g @powerkit_separator_style 'rounded'
    set -g @powerkit_elements_spacing 'both'
    set -g @powerkit_plugin_git_max_length 60
    set -g @powerkit_plugin_git_show_files true
    set -g @powerkit_plugin_git_show_branch true

# set -g @plugin 'https://gitlab.com/motaz-shokry/gruvbox-tmux'
#   set -g @gruvbox-tmux_theme 'medium'  # medium | soft | Default is hard  
#   set -g @gruvbox-tmux_transparent 0   # 1 | 0

# Setup `qof` plugins
set -g @plugin 'b0o/tmux-autoreload'  # autoreload `tmux.conf`
    set -g @tmux-autoreload-quiet 0
    set -g @tmux-autoreload-configs 1

set -g @plugin 'azorng/tmux-smooth-scroll'  # smooth scroll

set -g @plugin 'tmux-plugins/tmux-sensible'  # opinionated defaults

set -g @plugin 'tmux-plugins/tmux-resurrect'  # restore environment

set -g @plugin 'tmux-plugins/tmux-continuum'  # restore environment
    set -g @continuum-boot off
    set -g @continuum-restore on
    set -g @continuum-boot-options 'xterm-256color'

set -g @plugin 'tmux-plugins/tmux-sessionist'  # session default bindings

# set -g @plugin 'thesast/tmux-transient-status'  # hide the status bar
#     set -g @transient-status-delay '0.5'
#     set -g @transient-status-stall '2.5'

set -g @plugin 'nhdaly/tmux-better-mouse-mode'  # better mouse behaviour

set -g @plugin 'tmux-plugins/tmux-pain-control'  # pane default bindings

# Setup tooling plugins
set -g @plugin 'laktak/extrakto'  # select text from `tmux` buffer - <prefix-tab>

set -g @plugin 'sainnhe/tmux-fzf'  # manage sessions via `fzf` - <prefix-F>

set -g @plugin 'wfxr/tmux-fzf-url'  # opening urls from browser - <prefix-u>

set -g @plugin 'omerxx/tmux-floax'  # pop tmux floating pane - <prefix-p>
    set -g @floax-width '80%'
    set -g @floax-height '80%'
    set -g @floax-text-color 'blue'
    set -g @floax-border-color 'green'

set -g @plugin 'datamadsen/nunchux'  # app launcher - <prefix-a>
    set -g @nunchux-key 'a'

set -g @plugin 'fcsonline/tmux-thumbs'  # copy from `tmux` pane - <prefix-o>
    set -g @thumbs-key 'o'

# Setup behaviour plugins
# Use `xdg` convention paths
set-environment -g TMUX_PLUGIN_MANAGER_PATH "$XDG_CACHE_HOME/tmux/plugins"

# Setup binding keys
unbind 'C-b'
bind-key '`' send-prefix
bind-key -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel 'pbcopy'  # allow copy with `floax`
bind R source-file ~/.config/tmux/tmux.conf \; display-message 'Config reloaded!'

# Setup options
set-option -g prefix '`'
set-option -g mouse 'on'
set-option -g base-index 1
set-option -g pane-base-index 1
set-option -g status-position 'bottom'
set-option -g default-terminal "xterm-256color"
set-option -g pane-border-status 'top'
set-option -g pane-border-format "#{prefix_highlight} #{tmux_gh_uname} #{pane_index}: #{d:pane_current_path}/#{b:pane_current_path}"
set-option -ga terminal-overrides ",xterm-256color: Tc"
# set-option -ga terminal-overrides ",wezterm:Tc"

# Start plugins
run "${XDG_CACHE_HOME}/tmux/plugins/tpm-redux/tpm"

# vim: syntax=conf
