set shell := ["bash", "-uc"]

# Commnands for `aws`

import '~/.config/just/lib/aws/ec2.just'
import '~/.config/just/lib/aws/rds.just'
import '~/.config/just/lib/aws/secret-manager.just'

# Commnands for `azure`

import '~/.config/just/lib/azure/apim.just'
import '~/.config/just/lib/azure/switch.just'
import '~/.config/just/lib/azure/network.just'
import '~/.config/just/lib/azure/key-vault.just'
import '~/.config/just/lib/azure/deployment.just'
import '~/.config/just/lib/azure/subscription.just'
import '~/.config/just/lib/azure/container-app.just'
import '~/.config/just/lib/azure/log-analytics.just'
import '~/.config/just/lib/azure/resource-group.just'
import '~/.config/just/lib/azure/cognitive-services.just'
import '~/.config/just/lib/azure/container-instance.just'

# Commnands for `github`

import '~/.config/just/lib/github/cicd.just'
import '~/.config/just/lib/github/ghcr.just'
import '~/.config/just/lib/github/repos.just'
import '~/.config/just/lib/github/release.just'
import '~/.config/just/lib/github/workflow.just'

# Commnands for `kubernetes`

import '~/.config/just/lib/kubernetes/pods.just'
import '~/.config/just/lib/kubernetes/helm.just'
import '~/.config/just/lib/kubernetes/argocd.just'
import '~/.config/just/lib/kubernetes/secrets.just'
import '~/.config/just/lib/kubernetes/services.just'
import '~/.config/just/lib/kubernetes/crossplane.just'

default:
    @just --global-justfile --list

# vim: et ts=4 sts=4 sw=4 syntax=just
